import Head from 'next/head'
import Navbar from '../../components/navbar'

const Tarifs = () => {
  return (
    <Navbar current={'tarifs'}>
      <Head>
        <title>Immersy - Tarifs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </Navbar>
  )
}

export default Tarifs
