import Head from 'next/head'
import Navbar from '../../components/navbar'
import Simulez from '../../components/tarifs/simulez'

const Tarifs = () => {
  return (
    <Navbar current={'tarifs'}>
      <Head>
        <title>Immersy - Tarifs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Simulez />
    </Navbar>
  )
}

export default Tarifs
