import Head from 'next/head'
import Navbar from '../../components/navbar'
import Simulez from '../../components/tarifs/simulez'
import TarifsCustom from '../../components/tarifs/tarifsCustom'
import Projet from '../../components/shared/projet'
import TarifsProjet from '../../components/tarifs/tarifsProjet'

const Tarifs = () => {
  return (
    <Navbar current={'tarifs'}>
      <Head>
        <title>Immersy - Tarifs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TarifsCustom />
      <Simulez />
      <TarifsProjet />
    </Navbar>
  )
}

export default Tarifs
