import TitreTarifs from '../../../components/tarifs/titreTarifs'
import Navbar from '../../../components/navbar'
import Head from 'next/head'
import TarifForm from '../../../components/tarifs/tarifForm'
import { useRouter } from 'next/router'

export const getServerSideProps = (context) => {
  return {
    props: {
      surface: context.query.surface || null,
    },
  }
}

const TarifContact = ({ surface }) => {
  const surfaceInfo = {
    title: 'Surface standard',
    subTitle: 'inférieure à 150 ',
  }

  if (surface == 'standard') {
    Object.assign(surfaceInfo, {
      title: 'Surface standard',
      subTitle: 'inférieure à 150 ',
    })
  } else if (surface == 'moyenne') {
    Object.assign(surfaceInfo, {
      title: 'Surface moyenne',
      subTitle: 'entre 150 et 300 ',
    })
  } else if (surface == 'grande') {
    Object.assign(surfaceInfo, {
      title: 'Surface grande',
      subTitle: 'supérieure à 300 ',
    })
  } else if (surface == 'custom' || surface == null) {
    Object.assign(surfaceInfo, {
      title: 'Surface sur-mesure',
      subTitle: 'à définir en ',
    })
  }

  const router = useRouter()

  const handleClickModal = () => {
    if (surface == null) {
      router.push('/contact')
    } else {
      router.push('/tarifs')
    }
  }

  return (
    <div>
      <Navbar current={'demandeTarif'}>
        <Head>
          <title>Immersy - Demande de tarif</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className="mt-32 md:mx-80">
          <button onClick={handleClickModal} className="font-thin mx-5 ">
            &#8592; Retour
          </button>
          <TitreTarifs surfaceInfo={surfaceInfo} />
          <TarifForm surfaceInfo={surfaceInfo} />
        </div>
      </Navbar>
    </div>
  )
}

export default TarifContact
