import TitreTarifs from '../../../components/tarifs/contact/titre'
import Navbar from '../../../components/navbar'
import Head from 'next/head'

export const getServerSideProps = (context) => {
  return {
    props: {
      surface: context.query.surface || null,
    },
  }
}

const TarifContact = ({ surface }) => {
  const surfaceInfo = {
    title: 'Surface standard',
    subTitle: 'inférieure à 150 ',
  }

  if (surface == 'standard' || surface == null) {
    Object.assign(surfaceInfo, {
      title: 'Surface standard',
      subTitle: 'inférieure à 150 ',
    })
  } else if (surface == 'moyenne') {
    Object.assign(surfaceInfo, {
      title: 'Surface moyenne',
      subTitle: 'entre 150 et 300 ',
    })
  } else if (surface == 'grande') {
    Object.assign(surfaceInfo, {
      title: 'Surface grande',
      subTitle: 'supérieure à 300 ',
    })
  }

  return (
    <div>
      <Navbar current={'demandeTarif'}>
        <Head>
          <title>Immersy - Demande de tarif</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <TitreTarifs surfaceInfo={surfaceInfo} />
      </Navbar>
    </div>
  )
}

export default TarifContact
