import Head from 'next/head'
import Navbar from '../../components/navbar'

const Services = () => {
  return (
    <Navbar>
      <Head>
        <title>Immersy - Services</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </Navbar>
  )
}

export default Services
