import Head from 'next/head'
import Navbar from '../../components/navbar'
import Base from '../../components/services/base'
import Besoins from '../../components/services/besoins'
import Partage from '../../components/services/partage'

const Services = () => {
  return (
    <Navbar>
      <Head>
        <title>Immersy - Services</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Besoins />
      <Base />
      <Partage />
    </Navbar>
  )
}

export default Services
