import Head from 'next/head'
import Navbar from '../../components/navbar'
import Realisation from '../../components/realisations/realisation'
import Container from '../../components/shared/container'
import Projet from '../../components/shared/projet'

const Realisations = () => {
  return (
    <Navbar current={'Nos réalisations'}>
      <Head>
        <title>Immersy - Realisations</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Realisation />
      <Container className="mt-12 ">
        <Projet blue={false} />
      </Container>
    </Navbar>
  )
}

export default Realisations
