import Head from 'next/head'
import Navbar from '../../components/navbar'

const Tarif = () => {
  return (
    <Navbar current={'tarif'}>
      <Head>
        <title>Immersy - Tarif</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </Navbar>
  )
}

export default Tarif
