import Head from 'next/head'
import Navbar from '../../components/navbar'

const Contact = () => {
  return (
    <Navbar current={'contact'}>
      <Head>
        <title>Immersy - Contact</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </Navbar>
  )
}

export default Contact
