import Head from 'next/head'
import { useState } from 'react'
import ContactDirect from '../../components/contact/contactDirect'
import ContactezNous from '../../components/contact/contactezNous'
import ModalForm from '../../components/contact/modalForm'
import Navbar from '../../components/navbar'

const Contact = () => {
  const [isSelected, setIsSelected] = useState(false)

  return (
    <Navbar current={'contact'}>
      <Head>
        <title>Immersy - Contact</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {isSelected ? (
        <div className="mx-5 mt-32">
          <ModalForm />
        </div>
      ) : (
        <>
          <ContactezNous
            isSelected={isSelected}
            setIsSelected={setIsSelected}
          />
          <ContactDirect />
        </>
      )}
    </Navbar>
  )
}

export default Contact
