import Head from 'next/head'
import Merci from '../../components/envoi/merci'
import Navbar from '../../components/navbar'
import Btn1 from '../../components/shared/btn1'

const Envoi = () => {
  return (
    <Navbar current={'envoi'}>
      <Head>
        <title>Immersy - Envoi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Merci />
    </Navbar>
  )
}

export default Envoi
