import Head from 'next/head'
import Navbar from '../components/navbar'
import Hero from '../components/home/hero'

import Description from '../components/shared/description'
import Container from '../components/shared/container'

export default function Home() {
  return (
    <Navbar>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container className=" mt-20">
        <Description
          color={'text-white'}
          text={
            'Chaque collaboration est unique, c’est pourquoi notre objectif est de vous apporter exactement ce dont vous avez besoin.'
          }
        />
      </Container>
    </Navbar>
  )
}
